name: "poker-planning-local"

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik-poker.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./compose/traefik/dynamic_conf.yml:/etc/traefik/dynamic_conf.yml

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_started
    env_file:
      - .env
    environment:
      - NEXTAUTH_URL=https://poker.${DOMAIN}
    labels:
      - "traefik.http.routers.app.rule=Host(`poker.${DOMAIN}`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver"

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    command: -p ${DATABASE_PORT}
    volumes:
      - database-volume:/var/lib/postgresql/data
    labels:
      - "traefik.tcp.routers.database.rule=HostSNI(`database-poker.${DOMAIN}`)"
      - "traefik.tcp.routers.database.entrypoints=tcp"
      - "traefik.tcp.routers.database.tls.certresolver=myresolver"
      - "traefik.tcp.services.database.loadbalancer.server.port=${DATABASE_PORT}"

volumes:
  database-volume: